name: customized_keyboard
description: Use custom keyboards in flutter.
version: 1.0.7
repository: https://github.com/dani-weiss/flutter_customized_keyboard.git

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=3.16.1"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter: